import 'package:test/test.dart';
import 'package:hero_common/hero_common.dart';
import 'mock_hero_repository.dart';
import 'mock_hero_service.dart';

HeroDataManager _createManager() {
  final constantsSet = Runtime.prepareConstantsSet();
  HeroShqlAdapter.registerHeroSchema(constantsSet);
  final runtime = Runtime.prepareRuntime(constantsSet);
  return HeroDataManager(
    MockHeroRepository(),
    runtime: runtime,
    constantsSet: constantsSet,
  );
}

void main() async {
  test('Can download Batman', () async {
    var heroService = MockHeroService();
    var heroDataManager = _createManager();
    await heroService.getById("70").then((batmanJson) async {
      var batman = await heroDataManager.heroFromJson(
        batmanJson!,
        DateTime.timestamp(),
      );
      expect(batman, isNotNull);
      expect(batman.name, "Batman");
    });
  });

  test('Can amend other Batman', () async {
    var heroService = MockHeroService();
    var heroDataManager = _createManager();
    await heroService.getById("69").then((batmanJson) async {
      var batman = await heroDataManager.heroFromJson(
        batmanJson!,
        DateTime.timestamp(),
      );
      expect(batman, isNotNull);
      expect(batman.name, "Batman");

      var amendment = {
        "biography": {"alignment": "bad"},
      };

      var amendedBatman = await batman.amendWith(amendment);
      expect(amendedBatman.version, 2);
      expect(amendedBatman.biography.alignment, Alignment.bad);
      expect(amendedBatman.biography.aliases, batman.biography.aliases);

      StringBuffer sb = StringBuffer();
      expect(batman.diff(amendedBatman, sb), true);
      expect(sb.toString(), '''Biography: Alignment: good -> bad
''');
      heroDataManager.persist(amendedBatman);
    });
  });

  test('Can parse most heros', () async {
    var oldHeightConflictResolver = Height.conflictResolver;
    var oldWeightConflictResolver = Weight.conflictResolver;
    try {
      var heightConflictResolver = Height.conflictResolver =
          FirstProvidedValueConflictResolver<Height>();
      var weightConflictResolver = Weight.conflictResolver =
          FirstProvidedValueConflictResolver<Weight>();

      var heroService = MockHeroService();
      var heroDataManager = _createManager();
      List<String> failures = [];
      var timestamp = DateTime.timestamp();
      for (int i = 1; i < 731; ++i) {
        await heroService.getById(i.toString()).then((heroJson) async {
          try {
            await heroDataManager.heroFromJson(heroJson!, timestamp);
          } catch (e) {
            failures.add(e.toString());
          }
        });
      }

      // No conflicts for height expected
      expect(heightConflictResolver.resolutionLog, []);

      // Yes, the expected failures are generated with this little snippet and pasted in. Code generation FTW!
      /*for (var error in weightConflictResolver.resolutionLog) {
        var escapedError = error.replaceAll('"', r'\"');
        print('"$escapedError",');
      }*/

      // Plenty of conflicts for weight expected
      expect(weightConflictResolver.resolutionLog, [
        "When parsing Appearance -> Weight for new hero with externalId: \"1\" and name: \"A-Bomb\": Conflicting weight information: metric '441 kg' (parsed from '441 kg') corresponds to '972 lb' after converting back to imperial -- expecting '444 kg' in order to match first value of '980 lb' (parsed from '980 lb'). Resolving by using first provided (imperial) value for weight: '980 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"4\" and name: \"Abomination\": Conflicting weight information: metric '441 kg' (parsed from '441 kg') corresponds to '972 lb' after converting back to imperial -- expecting '444 kg' in order to match first value of '980 lb' (parsed from '980 lb'). Resolving by using first provided (imperial) value for weight: '980 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"10\" and name: \"Agent Bob\": Conflicting weight information: metric '81 kg' (parsed from '81 kg') corresponds to '179 lb' after converting back to imperial -- expecting '82 kg' in order to match first value of '181 lb' (parsed from '181 lb'). Resolving by using first provided (imperial) value for weight: '181 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"14\" and name: \"Alan Scott\": Conflicting weight information: metric '90 kg' (parsed from '90 kg') corresponds to '198 lb' after converting back to imperial -- expecting '91 kg' in order to match first value of '201 lb' (parsed from '201 lb'). Resolving by using first provided (imperial) value for weight: '201 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"18\" and name: \"Alien\": Conflicting weight information: metric '169 kg' (parsed from '169 kg') corresponds to '373 lb' after converting back to imperial -- expecting '170 kg' in order to match first value of '375 lb' (parsed from '375 lb'). Resolving by using first provided (imperial) value for weight: '375 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"20\" and name: \"Amazo\": Conflicting weight information: metric '173 kg' (parsed from '173 kg') corresponds to '381 lb' after converting back to imperial -- expecting '174 kg' in order to match first value of '385 lb' (parsed from '385 lb'). Resolving by using first provided (imperial) value for weight: '385 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"21\" and name: \"Ammo\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"34\" and name: \"Anti-Venom\": Conflicting weight information: metric '358 kg' (parsed from '358 kg') corresponds to '789 lb' after converting back to imperial -- expecting '360 kg' in order to match first value of '795 lb' (parsed from '795 lb'). Resolving by using first provided (imperial) value for weight: '795 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"35\" and name: \"Apocalypse\": Conflicting weight information: metric '135 kg' (parsed from '135 kg') corresponds to '298 lb' after converting back to imperial -- expecting '136 kg' in order to match first value of '300 lb' (parsed from '300 lb'). Resolving by using first provided (imperial) value for weight: '300 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"38\" and name: \"Aquaman\": Conflicting weight information: metric '146 kg' (parsed from '146 kg') corresponds to '322 lb' after converting back to imperial -- expecting '147 kg' in order to match first value of '325 lb' (parsed from '325 lb'). Resolving by using first provided (imperial) value for weight: '325 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"48\" and name: \"Atlas\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"49\" and name: \"Atlas\": Conflicting weight information: metric '126 kg' (parsed from '126 kg') corresponds to '278 lb' after converting back to imperial -- expecting '127 kg' in order to match first value of '280 lb' (parsed from '280 lb'). Resolving by using first provided (imperial) value for weight: '280 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"60\" and name: \"Bane\": Conflicting weight information: metric '180 kg' (parsed from '180 kg') corresponds to '397 lb' after converting back to imperial -- expecting '181 kg' in order to match first value of '400 lb' (parsed from '400 lb'). Resolving by using first provided (imperial) value for weight: '400 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"75\" and name: \"Beast\": Conflicting weight information: metric '181 kg' (parsed from '181 kg') corresponds to '399 lb' after converting back to imperial -- expecting '182 kg' in order to match first value of '402 lb' (parsed from '402 lb'). Resolving by using first provided (imperial) value for weight: '402 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"79\" and name: \"Beta Ray Bill\": Conflicting weight information: metric '216 kg' (parsed from '216 kg') corresponds to '476 lb' after converting back to imperial -- expecting '217 kg' in order to match first value of '480 lb' (parsed from '480 lb'). Resolving by using first provided (imperial) value for weight: '480 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"81\" and name: \"Big Barda\": Conflicting weight information: metric '135 kg' (parsed from '135 kg') corresponds to '298 lb' after converting back to imperial -- expecting '136 kg' in order to match first value of '300 lb' (parsed from '300 lb'). Resolving by using first provided (imperial) value for weight: '300 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"93\" and name: \"Bizarro\": Conflicting weight information: metric '155 kg' (parsed from '155 kg') corresponds to '342 lb' after converting back to imperial -- expecting '156 kg' in order to match first value of '345 lb' (parsed from '345 lb'). Resolving by using first provided (imperial) value for weight: '345 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"119\" and name: \"Blob\": Conflicting weight information: metric '230 kg' (parsed from '230 kg') corresponds to '507 lb' after converting back to imperial -- expecting '231 kg' in order to match first value of '510 lb' (parsed from '510 lb'). Resolving by using first provided (imperial) value for weight: '510 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"120\" and name: \"Bloodaxe\": Conflicting weight information: metric '495 kg' (parsed from '495 kg') corresponds to '1091 lb' after converting back to imperial -- expecting '498 kg' in order to match first value of '1100 lb' (parsed from '1100 lb'). Resolving by using first provided (imperial) value for weight: '1100 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"134\" and name: \"Box III\": Conflicting weight information: metric '110 kg' (parsed from '110 kg') corresponds to '243 lb' after converting back to imperial -- expecting '111 kg' in order to match first value of '245 lb' (parsed from '245 lb'). Resolving by using first provided (imperial) value for weight: '245 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"136\" and name: \"Brainiac\": Conflicting weight information: metric '135 kg' (parsed from '135 kg') corresponds to '298 lb' after converting back to imperial -- expecting '136 kg' in order to match first value of '300 lb' (parsed from '300 lb'). Resolving by using first provided (imperial) value for weight: '300 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"148\" and name: \"Cannonball\": Conflicting weight information: metric '81 kg' (parsed from '81 kg') corresponds to '179 lb' after converting back to imperial -- expecting '82 kg' in order to match first value of '181 lb' (parsed from '181 lb'). Resolving by using first provided (imperial) value for weight: '181 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"156\" and name: \"Captain Marvel\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"177\" and name: \"Citizen Steel\": Conflicting weight information: metric '170 kg' (parsed from '170 kg') corresponds to '375 lb' after converting back to imperial -- expecting '171 kg' in order to match first value of '378 lb' (parsed from '378 lb'). Resolving by using first provided (imperial) value for weight: '378 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"185\" and name: \"Colossus\": Conflicting weight information: metric '225 kg' (parsed from '225 kg') corresponds to '496 lb' after converting back to imperial -- expecting '226 kg' in order to match first value of '500 lb' (parsed from '500 lb'). Resolving by using first provided (imperial) value for weight: '500 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"194\" and name: \"Cyborg\": Conflicting weight information: metric '173 kg' (parsed from '173 kg') corresponds to '381 lb' after converting back to imperial -- expecting '174 kg' in order to match first value of '385 lb' (parsed from '385 lb'). Resolving by using first provided (imperial) value for weight: '385 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"204\" and name: \"Darkseid\": Conflicting weight information: metric '817 kg' (parsed from '817 kg') corresponds to '1801 lb' after converting back to imperial -- expecting '823 kg' in order to match first value of '1815 lb' (parsed from '1815 lb'). Resolving by using first provided (imperial) value for weight: '1815 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"208\" and name: \"Darth Vader\": Conflicting weight information: metric '135 kg' (parsed from '135 kg') corresponds to '298 lb' after converting back to imperial -- expecting '136 kg' in order to match first value of '300 lb' (parsed from '300 lb'). Resolving by using first provided (imperial) value for weight: '300 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"212\" and name: \"Deadman\": Conflicting weight information: metric '90 kg' (parsed from '90 kg') corresponds to '198 lb' after converting back to imperial -- expecting '91 kg' in order to match first value of '201 lb' (parsed from '201 lb'). Resolving by using first provided (imperial) value for weight: '201 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"215\" and name: \"Deathlok\": Conflicting weight information: metric '178 kg' (parsed from '178 kg') corresponds to '392 lb' after converting back to imperial -- expecting '179 kg' in order to match first value of '395 lb' (parsed from '395 lb'). Resolving by using first provided (imperial) value for weight: '395 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"216\" and name: \"Deathstroke\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"218\" and name: \"Destroyer\": Conflicting weight information: metric '383 kg' (parsed from '383 kg') corresponds to '844 lb' after converting back to imperial -- expecting '385 kg' in order to match first value of '850 lb' (parsed from '850 lb'). Resolving by using first provided (imperial) value for weight: '850 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"221\" and name: \"Doc Samson\": Conflicting weight information: metric '171 kg' (parsed from '171 kg') corresponds to '377 lb' after converting back to imperial -- expecting '172 kg' in order to match first value of '380 lb' (parsed from '380 lb'). Resolving by using first provided (imperial) value for weight: '380 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"222\" and name: \"Doctor Doom\": Conflicting weight information: metric '187 kg' (parsed from '187 kg') corresponds to '412 lb' after converting back to imperial -- expecting '188 kg' in order to match first value of '415 lb' (parsed from '415 lb'). Resolving by using first provided (imperial) value for weight: '415 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"225\" and name: \"Doctor Octopus\": Conflicting weight information: metric '110 kg' (parsed from '110 kg') corresponds to '243 lb' after converting back to imperial -- expecting '111 kg' in order to match first value of '245 lb' (parsed from '245 lb'). Resolving by using first provided (imperial) value for weight: '245 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"230\" and name: \"Doomsday\": Conflicting weight information: metric '412 kg' (parsed from '412 kg') corresponds to '908 lb' after converting back to imperial -- expecting '415 kg' in order to match first value of '915 lb' (parsed from '915 lb'). Resolving by using first provided (imperial) value for weight: '915 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"234\" and name: \"Drax the Destroyer\": Conflicting weight information: metric '306 kg' (parsed from '306 kg') corresponds to '675 lb' after converting back to imperial -- expecting '308 kg' in order to match first value of '680 lb' (parsed from '680 lb'). Resolving by using first provided (imperial) value for weight: '680 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"246\" and name: \"Etrigan\": Conflicting weight information: metric '203 kg' (parsed from '203 kg') corresponds to '448 lb' after converting back to imperial -- expecting '205 kg' in order to match first value of '452 lb' (parsed from '452 lb'). Resolving by using first provided (imperial) value for weight: '452 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"250\" and name: \"Fabian Cortez\": Conflicting weight information: metric '96 kg' (parsed from '96 kg') corresponds to '212 lb' after converting back to imperial -- expecting '97 kg' in order to match first value of '214 lb' (parsed from '214 lb'). Resolving by using first provided (imperial) value for weight: '214 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"256\" and name: \"Fin Fang Foom\": Conflicting weight information: metric '18 tons' (parsed from '18 tons') corresponds to '39683 lb' after converting back to imperial -- expecting '18143 kg' in order to match first value of '40000 lb' (parsed from '40000 lb'). Resolving by using first provided (imperial) value for weight: '40000 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"273\" and name: \"Galactus\": Conflicting weight information: metric '16 tons' (parsed from '16 tons') corresponds to '35274 lb' after converting back to imperial -- expecting '16510 kg' in order to match first value of '36400 lb' (parsed from '36400 lb'). Resolving by using first provided (imperial) value for weight: '36400 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"284\" and name: \"Giganta\": Conflicting weight information: metric '630 kg' (parsed from '630 kg') corresponds to '1389 lb' after converting back to imperial -- expecting '635 kg' in order to match first value of '1400 lb' (parsed from '1400 lb'). Resolving by using first provided (imperial) value for weight: '1400 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"285\" and name: \"Gladiator\": Conflicting weight information: metric '268 kg' (parsed from '268 kg') corresponds to '591 lb' after converting back to imperial -- expecting '269 kg' in order to match first value of '595 lb' (parsed from '595 lb'). Resolving by using first provided (imperial) value for weight: '595 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"287\" and name: \"Godzilla\": Conflicting weight information: metric '90,000 tons' (parsed from '90,000 tons') corresponds to '198416036 lb' after converting back to imperial -- expecting '90718474 kg' in order to match first value of '200000000 lb' (parsed from '200000000 lb'). Resolving by using first provided (imperial) value for weight: '200000000 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"294\" and name: \"Gorilla Grodd\": Conflicting weight information: metric '270 kg' (parsed from '270 kg') corresponds to '595 lb' after converting back to imperial -- expecting '272 kg' in order to match first value of '600 lb' (parsed from '600 lb'). Resolving by using first provided (imperial) value for weight: '600 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"295\" and name: \"Granny Goodness\": Conflicting weight information: metric '115 kg' (parsed from '115 kg') corresponds to '254 lb' after converting back to imperial -- expecting '116 kg' in order to match first value of '256 lb' (parsed from '256 lb'). Resolving by using first provided (imperial) value for weight: '256 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"303\" and name: \"Groot\": Conflicting weight information: metric '4 tons' (parsed from '4 tons') corresponds to '8818 lb' after converting back to imperial -- expecting '3719 kg' in order to match first value of '8200 lb' (parsed from '8200 lb'). Resolving by using first provided (imperial) value for weight: '8200 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"321\" and name: \"Hela\": Conflicting weight information: metric '225 kg' (parsed from '225 kg') corresponds to '496 lb' after converting back to imperial -- expecting '226 kg' in order to match first value of '500 lb' (parsed from '500 lb'). Resolving by using first provided (imperial) value for weight: '500 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"325\" and name: \"Hercules\": Conflicting weight information: metric '146 kg' (parsed from '146 kg') corresponds to '322 lb' after converting back to imperial -- expecting '147 kg' in order to match first value of '325 lb' (parsed from '325 lb'). Resolving by using first provided (imperial) value for weight: '325 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"332\" and name: \"Hulk\": Conflicting weight information: metric '630 kg' (parsed from '630 kg') corresponds to '1389 lb' after converting back to imperial -- expecting '635 kg' in order to match first value of '1400 lb' (parsed from '1400 lb'). Resolving by using first provided (imperial) value for weight: '1400 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"336\" and name: \"Hybrid\": Conflicting weight information: metric '77 kg' (parsed from '77 kg') corresponds to '170 lb' after converting back to imperial -- expecting '78 kg' in order to match first value of '172 lb' (parsed from '172 lb'). Resolving by using first provided (imperial) value for weight: '172 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"337\" and name: \"Hydro-Man\": Conflicting weight information: metric '119 kg' (parsed from '119 kg') corresponds to '262 lb' after converting back to imperial -- expecting '120 kg' in order to match first value of '265 lb' (parsed from '265 lb'). Resolving by using first provided (imperial) value for weight: '265 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"338\" and name: \"Hyperion\": Conflicting weight information: metric '207 kg' (parsed from '207 kg') corresponds to '456 lb' after converting back to imperial -- expecting '208 kg' in order to match first value of '460 lb' (parsed from '460 lb'). Resolving by using first provided (imperial) value for weight: '460 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"346\" and name: \"Iron Man\": Conflicting weight information: metric '191 kg' (parsed from '191 kg') corresponds to '421 lb' after converting back to imperial -- expecting '192 kg' in order to match first value of '425 lb' (parsed from '425 lb'). Resolving by using first provided (imperial) value for weight: '425 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"347\" and name: \"Iron Monger\": Conflicting weight information: metric '2 tons' (parsed from '2 tons') corresponds to '4409 lb' after converting back to imperial -- expecting '1918 kg' in order to match first value of '4230 lb' (parsed from '4230 lb'). Resolving by using first provided (imperial) value for weight: '4230 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"351\" and name: \"Jack-Jack\": Conflicting weight information: metric '14 kg' (parsed from '14 kg') corresponds to '31 lb' after converting back to imperial -- expecting '13 kg' in order to match first value of '30 lb' (parsed from '30 lb'). Resolving by using first provided (imperial) value for weight: '30 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"368\" and name: \"John Stewart\": Conflicting weight information: metric '90 kg' (parsed from '90 kg') corresponds to '198 lb' after converting back to imperial -- expecting '91 kg' in order to match first value of '201 lb' (parsed from '201 lb'). Resolving by using first provided (imperial) value for weight: '201 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"370\" and name: \"Joker\": Conflicting weight information: metric '86 kg' (parsed from '86 kg') corresponds to '190 lb' after converting back to imperial -- expecting '87 kg' in order to match first value of '192 lb' (parsed from '192 lb'). Resolving by using first provided (imperial) value for weight: '192 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"374\" and name: \"Juggernaut\": Conflicting weight information: metric '855 kg' (parsed from '855 kg') corresponds to '1885 lb' after converting back to imperial -- expecting '861 kg' in order to match first value of '1900 lb' (parsed from '1900 lb'). Resolving by using first provided (imperial) value for weight: '1900 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"386\" and name: \"Killer Croc\": Conflicting weight information: metric '356 kg' (parsed from '356 kg') corresponds to '785 lb' after converting back to imperial -- expecting '358 kg' in order to match first value of '790 lb' (parsed from '790 lb'). Resolving by using first provided (imperial) value for weight: '790 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"388\" and name: \"Kilowog\": Conflicting weight information: metric '324 kg' (parsed from '324 kg') corresponds to '714 lb' after converting back to imperial -- expecting '326 kg' in order to match first value of '720 lb' (parsed from '720 lb'). Resolving by using first provided (imperial) value for weight: '720 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"389\" and name: \"King Kong\": Conflicting weight information: metric '9,000 tons' (parsed from '9,000 tons') corresponds to '19841604 lb' after converting back to imperial -- expecting '9071847 kg' in order to match first value of '20000000 lb' (parsed from '20000000 lb'). Resolving by using first provided (imperial) value for weight: '20000000 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"391\" and name: \"Kingpin\": Conflicting weight information: metric '203 kg' (parsed from '203 kg') corresponds to '448 lb' after converting back to imperial -- expecting '204 kg' in order to match first value of '450 lb' (parsed from '450 lb'). Resolving by using first provided (imperial) value for weight: '450 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"409\" and name: \"Living Brain\": Conflicting weight information: metric '360 kg' (parsed from '360 kg') corresponds to '794 lb' after converting back to imperial -- expecting '362 kg' in order to match first value of '800 lb' (parsed from '800 lb'). Resolving by using first provided (imperial) value for weight: '800 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"412\" and name: \"Lizard\": Conflicting weight information: metric '230 kg' (parsed from '230 kg') corresponds to '507 lb' after converting back to imperial -- expecting '231 kg' in order to match first value of '510 lb' (parsed from '510 lb'). Resolving by using first provided (imperial) value for weight: '510 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"413\" and name: \"Lobo\": Conflicting weight information: metric '288 kg' (parsed from '288 kg') corresponds to '635 lb' after converting back to imperial -- expecting '290 kg' in order to match first value of '640 lb' (parsed from '640 lb'). Resolving by using first provided (imperial) value for weight: '640 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"414\" and name: \"Loki\": Conflicting weight information: metric '236 kg' (parsed from '236 kg') corresponds to '520 lb' after converting back to imperial -- expecting '238 kg' in order to match first value of '525 lb' (parsed from '525 lb'). Resolving by using first provided (imperial) value for weight: '525 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"416\" and name: \"Luke Cage\": Conflicting weight information: metric '191 kg' (parsed from '191 kg') corresponds to '421 lb' after converting back to imperial -- expecting '192 kg' in order to match first value of '425 lb' (parsed from '425 lb'). Resolving by using first provided (imperial) value for weight: '425 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"422\" and name: \"Machine Man\": Conflicting weight information: metric '383 kg' (parsed from '383 kg') corresponds to '844 lb' after converting back to imperial -- expecting '385 kg' in order to match first value of '850 lb' (parsed from '850 lb'). Resolving by using first provided (imperial) value for weight: '850 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"428\" and name: \"Man-Thing\": Conflicting weight information: metric '225 kg' (parsed from '225 kg') corresponds to '496 lb' after converting back to imperial -- expecting '226 kg' in order to match first value of '500 lb' (parsed from '500 lb'). Resolving by using first provided (imperial) value for weight: '500 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"432\" and name: \"Martian Manhunter\": Conflicting weight information: metric '135 kg' (parsed from '135 kg') corresponds to '298 lb' after converting back to imperial -- expecting '136 kg' in order to match first value of '300 lb' (parsed from '300 lb'). Resolving by using first provided (imperial) value for weight: '300 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"452\" and name: \"Mimic\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"460\" and name: \"Mister Sinister\": Conflicting weight information: metric '128 kg' (parsed from '128 kg') corresponds to '282 lb' after converting back to imperial -- expecting '129 kg' in order to match first value of '285 lb' (parsed from '285 lb'). Resolving by using first provided (imperial) value for weight: '285 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"463\" and name: \"MODOK\": Conflicting weight information: metric '338 kg' (parsed from '338 kg') corresponds to '745 lb' after converting back to imperial -- expecting '340 kg' in order to match first value of '750 lb' (parsed from '750 lb'). Resolving by using first provided (imperial) value for weight: '750 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"467\" and name: \"Molten Man\": Conflicting weight information: metric '248 kg' (parsed from '248 kg') corresponds to '547 lb' after converting back to imperial -- expecting '249 kg' in order to match first value of '550 lb' (parsed from '550 lb'). Resolving by using first provided (imperial) value for weight: '550 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"470\" and name: \"Moon Knight\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"481\" and name: \"Namor\": Conflicting weight information: metric '125 kg' (parsed from '125 kg') corresponds to '276 lb' after converting back to imperial -- expecting '126 kg' in order to match first value of '278 lb' (parsed from '278 lb'). Resolving by using first provided (imperial) value for weight: '278 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"484\" and name: \"Namorita\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"489\" and name: \"Nick Fury\": Conflicting weight information: metric '99 kg' (parsed from '99 kg') corresponds to '218 lb' after converting back to imperial -- expecting '100 kg' in order to match first value of '221 lb' (parsed from '221 lb'). Resolving by using first provided (imperial) value for weight: '221 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"498\" and name: \"Odin\": Conflicting weight information: metric '293 kg' (parsed from '293 kg') corresponds to '646 lb' after converting back to imperial -- expecting '294 kg' in order to match first value of '650 lb' (parsed from '650 lb'). Resolving by using first provided (imperial) value for weight: '650 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"500\" and name: \"Omega Red\": Conflicting weight information: metric '191 kg' (parsed from '191 kg') corresponds to '421 lb' after converting back to imperial -- expecting '192 kg' in order to match first value of '425 lb' (parsed from '425 lb'). Resolving by using first provided (imperial) value for weight: '425 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"504\" and name: \"Onslaught\": Conflicting weight information: metric '405 kg' (parsed from '405 kg') corresponds to '893 lb' after converting back to imperial -- expecting '408 kg' in order to match first value of '900 lb' (parsed from '900 lb'). Resolving by using first provided (imperial) value for weight: '900 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"526\" and name: \"Predator\": Conflicting weight information: metric '234 kg' (parsed from '234 kg') corresponds to '516 lb' after converting back to imperial -- expecting '235 kg' in order to match first value of '520 lb' (parsed from '520 lb'). Resolving by using first provided (imperial) value for weight: '520 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"547\" and name: \"Red Hulk\": Conflicting weight information: metric '630 kg' (parsed from '630 kg') corresponds to '1389 lb' after converting back to imperial -- expecting '635 kg' in order to match first value of '1400 lb' (parsed from '1400 lb'). Resolving by using first provided (imperial) value for weight: '1400 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"551\" and name: \"Red Tornado\": Conflicting weight information: metric '146 kg' (parsed from '146 kg') corresponds to '322 lb' after converting back to imperial -- expecting '147 kg' in order to match first value of '325 lb' (parsed from '325 lb'). Resolving by using first provided (imperial) value for weight: '325 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"556\" and name: \"Rhino\": Conflicting weight information: metric '320 kg' (parsed from '320 kg') corresponds to '705 lb' after converting back to imperial -- expecting '322 kg' in order to match first value of '710 lb' (parsed from '710 lb'). Resolving by using first provided (imperial) value for weight: '710 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"562\" and name: \"Robin II\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"570\" and name: \"Sabretooth\": Conflicting weight information: metric '171 kg' (parsed from '171 kg') corresponds to '377 lb' after converting back to imperial -- expecting '172 kg' in order to match first value of '380 lb' (parsed from '380 lb'). Resolving by using first provided (imperial) value for weight: '380 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"572\" and name: \"Sandman\": Conflicting weight information: metric '203 kg' (parsed from '203 kg') corresponds to '448 lb' after converting back to imperial -- expecting '204 kg' in order to match first value of '450 lb' (parsed from '450 lb'). Resolving by using first provided (imperial) value for weight: '450 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"573\" and name: \"Sasquatch\": Conflicting weight information: metric '900 kg' (parsed from '900 kg') corresponds to '1984 lb' after converting back to imperial -- expecting '907 kg' in order to match first value of '2000 lb' (parsed from '2000 lb'). Resolving by using first provided (imperial) value for weight: '2000 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"581\" and name: \"Scorpion\": Conflicting weight information: metric '310 kg' (parsed from '310 kg') corresponds to '683 lb' after converting back to imperial -- expecting '312 kg' in order to match first value of '689 lb' (parsed from '689 lb'). Resolving by using first provided (imperial) value for weight: '689 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"589\" and name: \"She-Hulk\": Conflicting weight information: metric '315 kg' (parsed from '315 kg') corresponds to '694 lb' after converting back to imperial -- expecting '317 kg' in order to match first value of '700 lb' (parsed from '700 lb'). Resolving by using first provided (imperial) value for weight: '700 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"590\" and name: \"She-Thing\": Conflicting weight information: metric '153 kg' (parsed from '153 kg') corresponds to '337 lb' after converting back to imperial -- expecting '154 kg' in order to match first value of '340 lb' (parsed from '340 lb'). Resolving by using first provided (imperial) value for weight: '340 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"594\" and name: \"Sif\": Conflicting weight information: metric '191 kg' (parsed from '191 kg') corresponds to '421 lb' after converting back to imperial -- expecting '192 kg' in order to match first value of '425 lb' (parsed from '425 lb'). Resolving by using first provided (imperial) value for weight: '425 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"598\" and name: \"Silver Surfer\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"605\" and name: \"Skaar\": Conflicting weight information: metric '180 kg' (parsed from '180 kg') corresponds to '397 lb' after converting back to imperial -- expecting '181 kg' in order to match first value of '400 lb' (parsed from '400 lb'). Resolving by using first provided (imperial) value for weight: '400 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"609\" and name: \"Solomon Grundy\": Conflicting weight information: metric '437 kg' (parsed from '437 kg') corresponds to '963 lb' after converting back to imperial -- expecting '440 kg' in order to match first value of '971 lb' (parsed from '971 lb'). Resolving by using first provided (imperial) value for weight: '971 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"612\" and name: \"Spawn\": Conflicting weight information: metric '405 kg' (parsed from '405 kg') corresponds to '893 lb' after converting back to imperial -- expecting '408 kg' in order to match first value of '900 lb' (parsed from '900 lb'). Resolving by using first provided (imperial) value for weight: '900 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"637\" and name: \"Steppenwolf\": Conflicting weight information: metric '91 kg' (parsed from '91 kg') corresponds to '201 lb' after converting back to imperial -- expecting '92 kg' in order to match first value of '203 lb' (parsed from '203 lb'). Resolving by using first provided (imperial) value for weight: '203 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"644\" and name: \"Superman\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"649\" and name: \"T-1000\": Conflicting weight information: metric '146 kg' (parsed from '146 kg') corresponds to '322 lb' after converting back to imperial -- expecting '147 kg' in order to match first value of '325 lb' (parsed from '325 lb'). Resolving by using first provided (imperial) value for weight: '325 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"651\" and name: \"T-850\": Conflicting weight information: metric '198 kg' (parsed from '198 kg') corresponds to '437 lb' after converting back to imperial -- expecting '199 kg' in order to match first value of '440 lb' (parsed from '440 lb'). Resolving by using first provided (imperial) value for weight: '440 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"655\" and name: \"Thanos\": Conflicting weight information: metric '443 kg' (parsed from '443 kg') corresponds to '977 lb' after converting back to imperial -- expecting '446 kg' in order to match first value of '985 lb' (parsed from '985 lb'). Resolving by using first provided (imperial) value for weight: '985 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"657\" and name: \"The Comedian\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"658\" and name: \"Thing\": Conflicting weight information: metric '225 kg' (parsed from '225 kg') corresponds to '496 lb' after converting back to imperial -- expecting '226 kg' in order to match first value of '500 lb' (parsed from '500 lb'). Resolving by using first provided (imperial) value for weight: '500 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"659\" and name: \"Thor\": Conflicting weight information: metric '288 kg' (parsed from '288 kg') corresponds to '635 lb' after converting back to imperial -- expecting '290 kg' in order to match first value of '640 lb' (parsed from '640 lb'). Resolving by using first provided (imperial) value for weight: '640 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"661\" and name: \"Thunderbird\": Conflicting weight information: metric '101 kg' (parsed from '101 kg') corresponds to '223 lb' after converting back to imperial -- expecting '102 kg' in order to match first value of '225 lb' (parsed from '225 lb'). Resolving by using first provided (imperial) value for weight: '225 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"664\" and name: \"Thunderstrike\": Conflicting weight information: metric '288 kg' (parsed from '288 kg') corresponds to '635 lb' after converting back to imperial -- expecting '290 kg' in order to match first value of '640 lb' (parsed from '640 lb'). Resolving by using first provided (imperial) value for weight: '640 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"666\" and name: \"Tiger Shark\": Conflicting weight information: metric '203 kg' (parsed from '203 kg') corresponds to '448 lb' after converting back to imperial -- expecting '204 kg' in order to match first value of '450 lb' (parsed from '450 lb'). Resolving by using first provided (imperial) value for weight: '450 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"680\" and name: \"Ultron\": Conflicting weight information: metric '331 kg' (parsed from '331 kg') corresponds to '730 lb' after converting back to imperial -- expecting '333 kg' in order to match first value of '735 lb' (parsed from '735 lb'). Resolving by using first provided (imperial) value for weight: '735 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"681\" and name: \"Utgard-Loki\": Conflicting weight information: metric '58 tons' (parsed from '58 tons') corresponds to '127868 lb' after converting back to imperial -- expecting '58059 kg' in order to match first value of '128000 lb' (parsed from '128000 lb'). Resolving by using first provided (imperial) value for weight: '128000 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"684\" and name: \"Valkyrie\": Conflicting weight information: metric '214 kg' (parsed from '214 kg') corresponds to '472 lb' after converting back to imperial -- expecting '215 kg' in order to match first value of '475 lb' (parsed from '475 lb'). Resolving by using first provided (imperial) value for weight: '475 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"689\" and name: \"Venom III\": Conflicting weight information: metric '334 kg' (parsed from '334 kg') corresponds to '736 lb' after converting back to imperial -- expecting '336 kg' in order to match first value of '742 lb' (parsed from '742 lb'). Resolving by using first provided (imperial) value for weight: '742 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"697\" and name: \"Vision\": Conflicting weight information: metric '135 kg' (parsed from '135 kg') corresponds to '298 lb' after converting back to imperial -- expecting '136 kg' in order to match first value of '300 lb' (parsed from '300 lb'). Resolving by using first provided (imperial) value for weight: '300 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"698\" and name: \"Vision II\": Conflicting weight information: metric '135 kg' (parsed from '135 kg') corresponds to '298 lb' after converting back to imperial -- expecting '136 kg' in order to match first value of '300 lb' (parsed from '300 lb'). Resolving by using first provided (imperial) value for weight: '300 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"702\" and name: \"Walrus\": Conflicting weight information: metric '162 kg' (parsed from '162 kg') corresponds to '357 lb' after converting back to imperial -- expecting '163 kg' in order to match first value of '360 lb' (parsed from '360 lb'). Resolving by using first provided (imperial) value for weight: '360 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"716\" and name: \"Wolfsbane\": Conflicting weight information: metric '473 kg' (parsed from '473 kg') corresponds to '1043 lb' after converting back to imperial -- expecting '476 kg' in order to match first value of '1050 lb' (parsed from '1050 lb'). Resolving by using first provided (imperial) value for weight: '1050 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"717\" and name: \"Wolverine\": Conflicting weight information: metric '135 kg' (parsed from '135 kg') corresponds to '298 lb' after converting back to imperial -- expecting '136 kg' in order to match first value of '300 lb' (parsed from '300 lb'). Resolving by using first provided (imperial) value for weight: '300 lb'.",
        "When parsing Appearance -> Weight for new hero with externalId: \"719\" and name: \"Wonder Man\": Conflicting weight information: metric '171 kg' (parsed from '171 kg') corresponds to '377 lb' after converting back to imperial -- expecting '172 kg' in order to match first value of '380 lb' (parsed from '380 lb'). Resolving by using first provided (imperial) value for weight: '380 lb'.",
      ]);

      // More code generation for the two actual failures:
      /*for (var error in failures) {
        var escapedError = error.replaceAll('"', r'\"');
        print('"$escapedError",');
      }*/

      // There are two known parsing failures for powerstats fields over 100%:
      expect(failures, [
        "FormatException: When parsing Powerstats -> Combat for new hero with externalId: \"43\" and name: \"Ares\": Percentage value must be within the range 0 to 100, inclusive, got: 101",
        "FormatException: When parsing Powerstats -> Durability for new hero with externalId: \"631\" and name: \"Stardust\": Percentage value must be within the range 0 to 100, inclusive, got: 110",
      ]);
    } finally {
      Height.conflictResolver = oldHeightConflictResolver;
      Weight.conflictResolver = oldWeightConflictResolver;
    }
  });
}
